[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz_runs = 256
optimizer = true
optimizer_runs = 10_000
# See more config options https://github.com/gakonst/foundry/tree/master/config

[profile.ci]
fuzz_runs = 1_000
verbosity = 4
